### ISSUE TITLE
broken with new update

### ISSUE THREAD

**Issue by developerfromjokela** [dala318/nordpool_planner#38]
Hi. thanks for new control via UI. but it's broken atm.

1. When two instances added, it shows all entities on all of them.
2. Automations don't react on state changes anymore -> rendering all automation useless atm.

Please fix them as they're making this plugin useless in its current version.

- DFJ

**Comment by dala318** [comment]
Feedback appreciated! I do need help testing it.
Hope you saw it was beta pre-release (with new HACS I see that it shows up a "new release" in HA settings, in previous HACS you needed to check the box "show pre-releases" for it to show up)

Your comment no1 I have seen from time to time but can't figure out why, I believe I set unique device identifiers for the entities but apparently not...

Can you elaborate on no2, you mean the integration do not react on changes in configuration, or on new hour (when new price range shall be updated)?
Otherwise "Automations" I interpret as those you have made that listens to the binary state "low cost". Does the state change for you but your automation do not react? Is so I would think it's not the integration...

**Comment by developerfromjokela** [comment]
> Feedback appreciated! I do need help testing it. Hope you saw it was beta pre-release (with new HACS I see that it shows up a "new release" in HA settings, in previous HACS you needed to check the box "show pre-releases" for it to show up)
> 
> Your comment no1 I have seen from time to time but can't figure out why, I believe I set unique device identifiers for the entities but apparently not...
> 
> Can you elaborate on no2, you mean the integration do not react on changes in configuration, or on new hour (when new price range shall be updated)? Otherwise "Automations" I interpret as those you have made that listens to the binary state "low cost". Does the state change for you but your automation do not react? Is so I would think it's not the integration...

No2: I have an automation that listens when low cost state changes, it triggers my automation. It doesnt get triggered at all with new update. I have two instances.

**Comment by dala318** [comment]
That's weird. 
But you see the state of the binary sensor change?
If you do, I can't see how it's the integration that causes it. Then it's more likely something in HA, have you made sure you use the correct entity-id in automation?
