### ISSUE TITLE
Date format for v2.0.0b4

### ISSUE THREAD

**Issue by Tom-ahawk** [dala318/nordpool_planner#41]
1)	Time is displayed with seconds.  Consider only showing hours and minutes, for space sawings in cards.
2)	number.nordpool_planner_search_length is set to max 23, why not 24? If I want the timespan within 24 hours it will skip one hour(?)
3)	I’ll give feedback if negative prices works when, next time prices are negative.

![image](https://github.com/user-attachments/assets/80493a23-9ef5-4051-9dbf-f621dc803a75)

**Comment by dala318** [comment]
About time format for I'll have a look if possible to change, it might be due to that I have set the [native_unit_of_measurement=UnitOfTime.HOURS](https://github.com/dala318/nordpool_planner/blob/main/custom_components/nordpool_planner/number.py#L35C5-L35C49) (but step-size is still 1 so only the hour part is used) and that then HomeAssistant "helps out" to display it like that. The minutes and seconds are not from the integration itself

Could be possible to extend even to 24h for the search_length but i wanted to be careful to not end up in some wrapping where the last hour would be interpreted as "now". But with the new search approach which actually uses proper `datetime` and adding `timedelta` it could still work extending to 24. If I get some time I might try to validate it and change. (or if you want, try modifying the [SEARCH_LENGTH_ENTITY_DESCRIPTION](https://github.com/dala318/nordpool_planner/blob/main/custom_components/nordpool_planner/number.py#L55) in your `custom_components` folder and see what happens)

**Comment by dala318** [comment]
For sake of not risk breaking anything I'll keep the limit of 23h.
The datetime format in UI I also have not found any way to modify so it will have to stay like that.
