### ISSUE TITLE
duration not working

### ISSUE THREAD

**Issue by ascii42** [dala318/nordpool_planner#65]
Hi,
after upgrade to 2.0.4 and migrate my old config, the duration  (i.e. 3 hours) is not working correctly.
i have configured a 3 hours duration for a device, the starttime is looks good, but after one hour the planner switches off,,,

does anybody has similar issues?

**Comment by dala318** [comment]
Is it always like this, that it turn off after 1 hour?
In that case can you supply a summary of your current config (accept cost/rate + duration & search-length) and a screenshot with history data (planner-state and price) and even better point out in time when you believe it should keep on.

**Comment by ascii42** [comment]
Maybe it‘s my fault, but i‘ve ported my config 1:1 from the configuration file to the new version, it could also be a bug (somewhere in the calculation i quess)

So here is my output

![IMG_6269](https://github.com/user-attachments/assets/b079c167-0209-43c7-bf21-6ead4b473ff9)
![IMG_6268](https://github.com/user-attachments/assets/5eba7a28-6f66-4722-a21a-37f165072e25)

**Comment by dala318** [comment]
What would help in understanding what's happening is if you could add a screenshot of state history like this, with at least 23h (your search length) after the faulty behavior of binary sensor.
![image](https://github.com/user-attachments/assets/f3c36117-65b5-4493-8d5f-f3afe9459e63)

Should maybe clarify that setting the duration to 5h as in your example does not guarantee that you get 5h consecutive ON. It's just the number of consecutive hours to average when searching for the lowest average cost.

So let's as example say you have a 5h time-span during **every night** where the electricity price is much cheaper than the rest of the hours (and have a 23h search length), you would then find that spot during the whole day and wait for it to happen, but halfway or so into that period the next nights cheap span will start appearing in the horizon of your search and if this average turn out to be cheaper than your current 5h average (from current hour and 5h forward) it will turn off and wait for the next night.

So if you really want to achieve a 5h consecutive ON-period you likely need to add some automation to the binary switch to ensure that. (I'll think of if it might be something to add to the integration, but a bit tricky to keep history data in internal logic, similar as I'm struggling with the "static" planner #54 )

**Comment by ascii42** [comment]
sure, here is a picture...

![duration](https://github.com/user-attachments/assets/19ea50a5-2dc6-4ccf-9564-4fe7cd8424d1)

i've also tried a shorter search length, but the example was nearly the same. (i.e. 11 hours ... ) and i'm shure that this worked before in version 1.6.

**Comment by ascii42** [comment]
![dryer-duration](https://github.com/user-attachments/assets/c01f082b-893e-4761-9936-080b48731043)

well, i've reduced my search lengh to 11 hours.
don't get me wrong, the update is pretty cool, but i'am really confused, that an block of 3 hours worked better for my devices before the update.

maybe it would be cool, to add an option to use an coherent duration or an split duration. (just an idea)

**Comment by dala318** [comment]
> but i'am really confused, that an block of 3 hours worked better for my devices before the update.

I don't think I have changed the expected design in that concern, but are some pretty large reworks in between v1 and v2. So either I have missed something in v2 (and if so I would like to know of it and fix), or it was actually a bug in v1 that worked in your favor but now is fixed.

If you can pin-point a specific time where you believe it should have stayed on, please share that history so that I can look in to the logic. (You should be able to add two integrations with different configurations)

> maybe it would be cool, to add an option to use an coherent duration or an split duration. (just an idea)

Yes agree, I have some todo on that part, most of it is mentioned in #54, but are some concerns that I don't know howe to tackle.
Most of it relates to persistent storage so that the integration behaves predictable even if home assistant is restarted.

Have you tried tweaking the "accept_rate" config? If you have a price profile as in last picture your average price should be in the area of 0.30, setting an accept-rate of 0,5 should then turn on for every price below 0,15.

**Comment by ascii42** [comment]
accept_rate is an good point i will try this.
meanwhile i‘ve purged an reinstalled the integration and my spooky problem seems to be gone, maybe just another ghost in the shell….
